{{- if and .Values.storage.comfy.enabled .Values.storage.comfy.smb.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: comfy-smb-secret
type: Opaque
stringData:
  username: {{ .Values.storage.comfy.smb.username | quote }}
  password: {{ .Values.storage.comfy.smb.password | quote }}
{{- end }}
